### PR TITLE
Search in correct package lib dir for required libraries

### PR DESCRIPTION
**Pull request by bgruening**
Its a bit problematic that the init function searches only in hardcoded path or requires the env var. This makes packaging very complicated. This fix is not ideal, but needed for a potential conda package. Ideally, this entire module system needs a restructuring to make it more flexible.

### CODE REVIEW

**Comment by jtfcordes** [comment]
Can you describe the problem in more detail?

I'm not sure how this fix works - maybe it's related to the conda packaging mechanics?

**Comment by bgruening** [comment]
Thanks for commenting @jtfcordes!

Python packages are usually installed into `site-packages` and there is no `bin` directory above the `site-package`. The shread-libraries should also not be in a `bin` directory, but rather in a `lib` directory. This all makes it very hard to package it up, unfortunately.

**Comment by jtfcordes** [comment]
So you're suggesting renaming bin to lib?
I don't think that's the problem - it's too easy - is it? 

Can you describe what your goal is and at what point you ran into problems?

**Comment by jtfcordes** [comment]
I don't see a hardcoded path - what do you mean by that?

The only hardcoded part is the search for libraries relative to the file “m2aia/\_\_init\_\_.py” in the “bin” directory (which will be adjusted to “lib” accordingly based on your suggestion). The search for libraries in this directory is intentional. The corresponding libraries are only supplied with the Python packages that are distributed via pypi (to avoid version conflicts). This package is not intended to be installed via src.

And by using the M2AIA_PATH environment variable, this can be bypassed - e.g. to use customized versions and self-compiled M2aia libraries.

**Pull request merged**
